config/routes.rb
Rails.application.routes.draw do
  root 'money_movements#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :categories
  resources :money_movements
  resources :users
  
  get 'profile/:id', to: 'users#show'

  namespace :api do
    resources :users, only: [:index, :create]
  end
end

app/models/money_movement.rb
class MoneyMovement < ApplicationRecord
  belongs_to :user

  has_many :category_money_movements, dependent: :destroy
  has_many :categories, through: :category_money_movements

  has_one :description, class_name: 'MoneyMovementDescription', dependent: :destroy

  validates_presence_of :amount
end

app/controllers/money_movements_controller.rb
class MoneyMovementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_money_movement, only: [:show, :edit, :update, :destroy]

  def index
    @money_movements =
      MoneyMovementDecorator.decorate_collection(current_user
                                                   .money_movements
                                                   .order(created_at: :desc)
                                                   .includes(:categories))
  end

  def show
  end

  def new
    @money_movement_form = MoneyMovementForm.new(MoneyMovement.new)
  end

  def edit
    @money_movement_form = MoneyMovementForm.new(@money_movement)
  end

  def create
    @money_movement_form =
      MoneyMovementForm.new(current_user.money_movements.build)

    if @money_movement_form.validate(money_movement_params)
      @money_movement_form.save
      redirect_to money_movements_path, notice: 'Money movement was successfully created.'
    else
      render :new
    end
  end

  def update
    @money_movement_form = MoneyMovementForm.new(@money_movement)

    if @money_movement_form.validate(money_movement_params)
      @money_movement_form.save
      redirect_to money_movements_path, notice: 'Money movement was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @money_movement.destroy
    redirect_to money_movements_url, notice: 'Money movement was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_money_movement
    @money_movement = MoneyMovement.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def money_movement_params
    params.require(:money_movement).permit(
      :amount,
      category_ids: [],
      description_attributes: [:body]
    )
  end
end

app/helpers/money_movements_helper.rb
module MoneyMovementsHelper
end

app/views/money_movements/_form.html.erb
<%= form_with(model: money_movement_form, local: true, url: url) do |form| %>
  <div class="row">
    <div class="col s12 m10 offset-m1">
      <% if money_movement_form.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(money_movement_form.errors.count, "error") %> prohibited this money_movement from being saved:</h2>

          <ul class="collection">
            <% money_movement_form.errors.full_messages.each do |message| %>
              <li class="collection-item red-text"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m6 offset-m3">
      <%= form.label :amount %>
      <%= form.text_field :amount, id: :money_movement_amount, class: 'money', autofocus: true %>
    </div>
  </div>

  <div class="row">
    <%= form.fields_for :description do |description_form| %>
      <div class="col s12 m6 offset-m3">
        <%= description_form.label :body %>
        <%= description_form.text_field :body %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |box| %>
      <div class="col s12 m6 offset-m3">
        <%= box.check_box %>
        <%= box.label %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="input-field col s12 m6 offset-m3 center">
      <%= form.submit class: 'btn blue lighten-1' %>
    </div>
  </div>
<% end %>

app/views/money_movements/edit.html.erb
<div class="row">
  <h1 class="center">Editing Money Movement</h1>
</div>

<%= render 'form', money_movement_form: @money_movement_form, url: money_movement_path(@money_movement_form) %>

<div class="row">
  <div class="col s12 center">
    <%= link_to 'Back', money_movements_path %>
  </div>
</div>

app/views/money_movements/index.html.erb
<div class="row">
  <h1 class="center">Money Movements</h1>
</div>

<div class="row">
  <div class="col s12 m10 offset-m1">
    <table>
      <thead>
        <tr>
          <th>Amount</th>
          <th>Categories</th>
          <th>Created at</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @money_movements.each do |money_movement| %>
          <tr>
            <%= content_tag :td, class: 'tooltipped', data: { tooltip: money_movement.description.body } do %>
              <%= money_movement.amount %>
            <% end %>
            <td><%= money_movement.categories_names_separated_by_comma %></td>
            <td><%= money_movement.created_at %></td>
            <td><%= link_to 'Edit', edit_money_movement_path(money_movement) %></td>
            <td><%= link_to 'Destroy', money_movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/money_movements/new.html.erb
<div class="row">
  <h1 class="center">New Money Movement</h1>
</div>

<%= render 'form', money_movement_form: @money_movement_form, url: money_movements_path %>

<div class="row">
  <div class="col s12 center">
    <%= link_to 'Back', money_movements_path %>
  </div>
</div>

app/views/money_movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @money_movement.amount %>
</p>

<%= link_to 'Edit', edit_money_movement_path(@money_movement) %> |
<%= link_to 'Back', money_movements_path %>