config/routes.rb
Rails.application.routes.draw do
  root 'money_movements#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :categories
  resources :money_movements
  resources :users
  
  get 'profile/:id', to: 'users#show'

  namespace :api do
    resources :users, only: [:index, :create]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_money_movements
  has_many :money_movements, through: :category_money_movements
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category_form = CategoryForm.new(Category.new)
  end

  def edit
    @category_form = CategoryForm.new(@category)
  end

  def create
    @category_form = CategoryForm.new(current_user.categories.build)

    if @category_form.validate(category_params)
      @category_form.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    @category_form = CategoryForm.new(@category)

    if @category_form.validate(category_params)
      @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category_form) do |form| %>
  <div class="row">
    <div class="col s12 m10 offset-m1">
      <% if category_form.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(category_form.errors.count, "error") %> prohibited this money_movement from being saved:</h2>

          <ul class="collection">
            <% category_form.errors.full_messages.each do |message| %>
              <li class="collection-item red-text"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="input-field col s12 m6 offset-m3">
        <%= form.label :name %>
        <%= form.text_field :name, id: :category_name %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m6 offset-m3 center">
      <%= form.submit class: 'btn blue lighten-1' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
  <h1 class="center">Editing Category</h1>
</div>

<%= render 'form', category_form: @category_form %>

<div class="row">
  <div class="col s12 center">
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="center">Categories</h1>

<div class="row">
  <div class="col s12 m10 offset-m1">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', edit_category_path(category.id) %></td>
            <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row">
  <h1 class="center">New Category</h1>
</div>

<%= render 'form', category_form: @category_form %>

<div class="row">
  <div class="col s12 center">
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.user_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>